### PR TITLE
UserRepo

### PR DESCRIPTION
**Pull request by ngthanh219**
## Related Tickets:
- [#33754](https://edu-redmine.sun-asterisk.vn/issues/33754)

## WHAT this PR does?
- Trong phần này, em viết các ```repository``` cho controlller User

## Notes Impacted Areas:
- N/A.

## Attachments:
- N/A.

### CODE REVIEW

**Review by Cho99 — APPROVED** [review]

**Comment by ngthanh219** [comment]
ready

**Review by huyenttm-0901 — COMMENTED** [review]
conflicted

**Comment by ngthanh219** [comment]
ready

**Comment by ngthanh219** [comment]
ready

**Review by huyenttm-0901 — APPROVED** [review]

**Pull request merged**
